title: Zeraora-807:A pokemon lover, especially fond of zeraora.
page-top-title: Zeraora-807:Ordinary Coder, Extraordinary Dreams.
top-section-bg-text: Zeraora so cute!
home-subtitle: Zeraora-807&ensp;|&ensp;Zeraora Lover
copyright-text: '&copy; Zeraora-807 2025. All Rights Reserved.'
